[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rewards_distributor = "Cfq4kv5pJJiTjqRoYJeYC4kF46a2ZMtBxqPSxnDxt2Qf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
